		<div class="u-footer">
			<div class="left">
				<p> Sign up for our newsletter<br>
				<input type="text" name="email" placeholder="-Your email">
				</p>
			</div>
			<div class="right">
				<p>
					New Business <br>
					<a href='mailto:jdimawea@uccs.edu'>jdimawea@uccs.edu</a>
				</p>
				<p>
					About Us <br>
					<a href='about.php'>View our story</a>
				</p>			
				<p>
					Location <br>
					<span class='location'>1420 Austin Bluffs Pkwy<br> Colorado Springs</span>
				</p>	
			</div>				
		</div>