		<div class="u-header">
			<a href='http://localhost/infs3800/ProjectDimaweaV4/php/index.php'><img src='../img/logo.png'></a>
			<nav>
				<a href='http://localhost/infs3800/ProjectDimaweaV4/php/index.php'>Home</a>
				<a href='http://localhost/infs3800/ProjectDimaweaV4/php/about.php'>About Us</a>
				<a href='http://localhost/infs3800/ProjectDimaweaV4/php/contact.php'>Contact Us</a>
				<!-- add logoff in php -->
				<a href='http://localhost/infs3800/ProjectDimaweaV4/php/login.php'>Login</a>
			</nav>			
		</div>