		<div class='l-footer'>
			<div class="left">
				<p> Sign up for our newsletter<br>
				<input type="text" name="email" value="-Your email">
				</p>
			</div>
			<div class="right">
				<p>
					New Business <br>
					<a href='mailto:jdimawea@uccs.edu'>jdimawea@uccs.edu</a>
				</p>
				<p>
					About Us <br>
					<a href='http://localhost/infs3800/ProjectDimaweaV3/php/about.php'>View our story</a>
				</p>			
				<p>
					Location <br>
					<span class='location'>1420 Austin Bluffs Pkwy<br> Colorado Springs</span>
				</p>	
			</div>			
		</div>