		<div class='l-header'>
			<a href='http://localhost/infs3800/ProjectDimaweaV3/php/index.php'><img src='../img/logo.png'></a>
			<nav>
				<a href='http://localhost/infs3800/ProjectDimaweaV3/php/index.php'>Home</a>
				<a href='http://localhost/infs3800/ProjectDimaweaV3/php/about.php'>About Us</a>
				<a href='http://localhost/infs3800/ProjectDimaweaV3/php/contact.php'>Contact Us</a>
				<!-- add logoff in php -->
				<a href='http://localhost/infs3800/ProjectDimaweaV3/php/login.php'>Login</a>
			</nav>
		</div> 